name: easy_sales
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  common:
    path: packages/common
  core:
    path: packages/core
  auth:
    path: packages/auth
  dashboard:
    path: packages/dashboard
  home:
    path: packages/home
  setting:
    path: packages/setting
  sales:
     path: packages/sales
  merchandiser:
    path: packages/merchandiser    
  profile:
    path: packages/profile
  report:
    path: packages/report

  flutter_riverpod: any
  go_router: any
  upgrader: any
  loader_overlay: any
  riverpod_annotation: any
  timezone: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.13
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.6.0
  # https://pub.dev/packages/freezed
  freezed: ^2.5.7
  # https://pub.dev/packages/riverpod_generator
  riverpod_generator: ^2.6.3
  # https://pub.dev/packages/riverpod_lint
  riverpod_lint: ^2.6.3
  # https://pub.dev/packages/custom_lint
  custom_lint: ^0.7.0

flutter:
  uses-material-design: true
