// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    settingEntity,
    merchandiserCustomerEntity,
    salesCustomerEntity,
    searchMerchandiserCustomerHistoryEntity,
    searchSalesCustomerHistoryEntity,
    searchProductHistoryEntity,
    customerAddressEntity,
    productEntity,
    productPriceEntity,
    salesHeaderEntity,
    salesLineEntity,
    customerId,
  ];
  late final Shape0 settingEntity = Shape0(
    source: i0.VersionedTable(
      entityName: 'setting_entity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 merchandiserCustomerEntity = Shape1(
    source: i0.VersionedTable(
      entityName: 'merchandiser_customer_entity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(customer_id)'],
      columns: [
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 salesCustomerEntity = Shape1(
    source: i0.VersionedTable(
      entityName: 'sales_customer_entity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(customer_id)'],
      columns: [
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 searchMerchandiserCustomerHistoryEntity = Shape2(
    source: i0.VersionedTable(
      entityName: 'search_merchandiser_customer_history_entity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 searchSalesCustomerHistoryEntity = Shape2(
    source: i0.VersionedTable(
      entityName: 'search_sales_customer_history_entity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 searchProductHistoryEntity = Shape2(
    source: i0.VersionedTable(
      entityName: 'search_product_history_entity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 customerAddressEntity = Shape3(
    source: i0.VersionedTable(
      entityName: 'customer_address_entity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(location)'],
      columns: [
        _column_2,
        _column_20,
        _column_21,
        _column_5,
        _column_10,
        _column_11,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 productEntity = Shape4(
    source: i0.VersionedTable(
      entityName: 'product_entity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(item_id)'],
      columns: [
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_19,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 productPriceEntity = Shape5(
    source: i0.VersionedTable(
      entityName: 'product_price_entity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(rec_id)'],
      columns: [
        _column_26,
        _column_27,
        _column_28,
        _column_34,
        _column_42,
        _column_43,
        _column_44,
        _column_36,
        _column_35,
        _column_45,
        _column_46,
        _column_47,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 salesHeaderEntity = Shape6(
    source: i0.VersionedTable(
      entityName: 'sales_header_entity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_48,
        _column_49,
        _column_2,
        _column_3,
        _column_50,
        _column_5,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 salesLineEntity = Shape7(
    source: i0.VersionedTable(
      entityName: 'sales_line_entity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_48,
        _column_59,
        _column_60,
        _column_28,
        _column_27,
        _column_29,
        _column_61,
        _column_34,
        _column_62,
        _column_35,
        _column_63,
        _column_64,
        _column_65,
        _column_40,
        _column_56,
        _column_57,
        _column_58,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index customerId = i1.Index(
    'customer_id',
    'CREATE INDEX customer_id ON customer_address_entity (customer_id)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get customerId =>
      columnsByName['customer_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerName =>
      columnsByName['customer_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get address =>
      columnsByName['address']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get salesPersonId =>
      columnsByName['sales_person_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get salesPerson =>
      columnsByName['sales_person']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get merchandiser =>
      columnsByName['merchandiser']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get countryId =>
      columnsByName['country_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phoneNumber =>
      columnsByName['phone_number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get latitude =>
      columnsByName['latitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get longitude =>
      columnsByName['longitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get creditLimit =>
      columnsByName['credit_limit']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get currencyCode =>
      columnsByName['currency_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get paymentTerm =>
      columnsByName['payment_term']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get priceGroup =>
      columnsByName['price_group']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customreDimension =>
      columnsByName['customre_dimension']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get status =>
      columnsByName['status']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get companyId =>
      columnsByName['company_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get companyCode =>
      columnsByName['company_code']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'customer_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'customer_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'address',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sales_person_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sales_person',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'merchandiser',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'country_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'phone_number',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_10(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'latitude',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_11(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'longitude',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_12(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'credit_limit',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'currency_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payment_term',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'price_group',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'customre_dimension',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'company_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'company_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get customerId =>
      columnsByName['customer_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deliveryName =>
      columnsByName['delivery_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get address =>
      columnsByName['address']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get salesPersonId =>
      columnsByName['sales_person_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get latitude =>
      columnsByName['latitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get longitude =>
      columnsByName['longitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get postalAddress =>
      columnsByName['postal_address']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isPrimary =>
      columnsByName['is_primary']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get companyCode =>
      columnsByName['company_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get companyId =>
      columnsByName['company_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'delivery_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'address',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'postal_address',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'location',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<bool> _column_24(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'is_primary',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("is_primary" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'company_code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get productId =>
      columnsByName['product_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get itemId =>
      columnsByName['item_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get productName =>
      columnsByName['product_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get barcode =>
      columnsByName['barcode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get itemGroup =>
      columnsByName['item_group']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get packSize =>
      columnsByName['pack_size']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get salesUnit =>
      columnsByName['sales_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get unitPrice =>
      columnsByName['unit_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get image =>
      columnsByName['image']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get itemDiscountGroup =>
      columnsByName['item_discount_group']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get itemFOCGroup =>
      columnsByName['item_f_o_c_group']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get inventDimId =>
      columnsByName['invent_dim_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get companyCode =>
      columnsByName['company_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get companyId =>
      columnsByName['company_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'product_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'item_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'product_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'barcode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'item_group',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pack_size',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sales_unit',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_36(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'unit_price',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'image',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'item_discount_group',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'item_f_o_c_group',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'invent_dim_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get productId =>
      columnsByName['product_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get itemId =>
      columnsByName['item_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get packSize =>
      columnsByName['pack_size']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get flavor =>
      columnsByName['flavor']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get fromDate =>
      columnsByName['from_date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get toDate =>
      columnsByName['to_date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<double> get unitPrice =>
      columnsByName['unit_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get salesUnit =>
      columnsByName['sales_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get currencyCode =>
      columnsByName['currency_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get priceGroup =>
      columnsByName['price_group']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get recId =>
      columnsByName['rec_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get companyId =>
      columnsByName['company_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get companyCode =>
      columnsByName['company_code']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'flavor',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<DateTime> _column_43(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'from_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<DateTime> _column_44(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'to_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'currency_code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'price_group',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'rec_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get salesId =>
      columnsByName['sales_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerId =>
      columnsByName['customer_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerName =>
      columnsByName['customer_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerAddress =>
      columnsByName['customer_address']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get salesPersonId =>
      columnsByName['sales_person_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerRequisition =>
      columnsByName['customer_requisition']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerPriceGroup =>
      columnsByName['customer_price_group']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deliveryAddressLocation =>
      columnsByName['delivery_address_location']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deliveryDate =>
      columnsByName['delivery_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get transactionDate =>
      columnsByName['transaction_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get syncStatus =>
      columnsByName['sync_status']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get companyId =>
      columnsByName['company_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'PRIMARY KEY AUTOINCREMENT',
      ),
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sales_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways('UNIQUE'),
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'customer_address',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'customer_requisition',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'customer_price_group',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'delivery_address_location',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'delivery_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'transaction_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'device_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sync_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get salesId =>
      columnsByName['sales_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lineId =>
      columnsByName['line_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get itemId =>
      columnsByName['item_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get productId =>
      columnsByName['product_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get productName =>
      columnsByName['product_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get productDescription =>
      columnsByName['product_description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get packSize =>
      columnsByName['pack_size']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get quantity =>
      columnsByName['quantity']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get salesUnit =>
      columnsByName['sales_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get salesPrice =>
      columnsByName['sales_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get taxAmount =>
      columnsByName['tax_amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lineAmount =>
      columnsByName['line_amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get inventDimId =>
      columnsByName['invent_dim_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get transactionDate =>
      columnsByName['transaction_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get syncStatus =>
      columnsByName['sync_status']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get companyId =>
      columnsByName['company_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sales_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES sales_header_entity (sales_id) ON DELETE CASCADE',
      ),
    );
i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'line_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'product_description',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_62(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'quantity',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_63(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sales_price',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_64(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'tax_amount',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_65(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'line_amount',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
