name: common
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 

  core:
    path: ../core

dependency_overrides:
  analyzer_plugin: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.13
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.6.0
  # https://pub.dev/packages/freezed
  freezed: ^2.5.7
  # https://pub.dev/packages/riverpod_generator
  riverpod_generator: ^2.6.3
  # https://pub.dev/packages/riverpod_lint
  riverpod_lint: ^2.6.3
  # https://pub.dev/packages/custom_lint
  custom_lint: ^0.7.0  
  # https://pub.dev/packages/flutter_translation_sheet
  flutter_translation_sheet: ^1.0.34
  # https://pub.dev/packages/flutter_gen_runner
  flutter_gen_runner: ^5.9.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

  assets:
    exclude:
      - assets/i18n/
      - google_fonts/
    outputs:
      package_parameter_enabled: true

  
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
      - assets/i18n/
      - assets/images/
      - google_fonts/

  
