name: core
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  common:
    path: ../common
  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.6.1
  # https://pub.dev/packages/riverpod_annotation
  riverpod_annotation: ^2.6.1
  # https://pub.dev/packages/dio
  dio: ^5.7.0
  # https://pub.dev/packages/dio_http_formatter
  dio_http_formatter: ^3.2.1
  # https://pub.dev/packages/retrofit
  retrofit: ^4.4.1
  # https://pub.dev/packages/go_router
  go_router: ^14.6.0
  # https://pub.dev/packages/logger
  logger: ^2.4.0
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub.dev/packages/camerawesome
  camerawesome: ^2.1.0
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.4
  # https://pub.dev/packages/multiple_result
  multiple_result: ^5.1.0
  # https://pub.dev/packages/upgrader
  upgrader: ^11.3.0
  # https://pub.dev/packages/loader_overlay
  loader_overlay: ^4.0.3
  # https://pub.dev/packages/loading_animation_widget
  loading_animation_widget: ^1.3.0
  # https://pub.dev/packages/google_fonts
  google_fonts: ^6.2.1
  # https://pub.dev/packages/gal
  gal: ^2.3.0
  # https://pub.dev/packages/open_file
  open_file: ^3.5.10
  # https://pub.dev/packages/image
  image: ^4.3.0
  # https://pub.dev/packages/intl
  intl: ^0.19.0
  # https://pub.dev/packages/timezone
  timezone: ^0.10.0
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.2
  # https://pub.dev/packages/envied
  envied: ^1.0.0
  # https://pub.dev/packages/drift
  drift: ^2.23.0
  # https://pub.dev/packages/drift_flutter
  drift_flutter: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.13
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.6.0
  # https://pub.dev/packages/freezed
  freezed: ^2.5.7
  # https://pub.dev/packages/riverpod_generator
  riverpod_generator: ^2.6.3
  # https://pub.dev/packages/envied_generator
  envied_generator: ^1.0.0
  # https://pub.dev/packages/drift_dev
  drift_dev: ^2.23.0

flutter:
  uses-material-design: true

