name: core
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  common:
    path: ../common
  auth:
    path: ../auth
  home:
    path: ../home
  dashboard:
    path: ../dashboard
  merchandiser:
    path: ../merchandiser
  profile:
    path: ../profile
  report:
    path: ../report
  sales:
    path: ../sales
  setting:
    path: ../setting
  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^3.0.0
  # https://pub.dev/packages/riverpod_annotation
  riverpod_annotation: ^3.0.0  
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^3.1.0
  # https://pub.dev/packages/dio
  dio: ^5.9.0
  # https://pub.dev/packages/dio_http_formatter
  dio_http_formatter: ^3.3.1
  # https://pub.dev/packages/retrofit
  retrofit: ^4.7.2
  # https://pub.dev/packages/go_router
  go_router: ^16.2.1
  # https://pub.dev/packages/logger
  logger: ^2.6.1
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub.dev/packages/camerawesome
  camerawesome: ^2.5.0
  # https://pub.dev/packages/multiple_result
  multiple_result: ^5.2.0
  # https://pub.dev/packages/upgrader
  upgrader: ^12.0.0
  # https://pub.dev/packages/loader_overlay
  loader_overlay: ^5.0.0
  # https://pub.dev/packages/loading_animation_widget
  loading_animation_widget: ^1.3.0
  # https://pub.dev/packages/google_fonts
  google_fonts: ^6.3.1
  # https://pub.dev/packages/gal
  gal: ^2.3.2
  # https://pub.dev/packages/open_file
  open_file: ^3.5.10
  # https://pub.dev/packages/image
  image: ^4.5.4
  # https://pub.dev/packages/intl
  intl: ^0.20.2
  # https://pub.dev/packages/timezone
  timezone: ^0.10.1
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.4
  # https://pub.dev/packages/envied
  envied: ^1.2.1
  # https://pub.dev/packages/drift
  drift: ^2.28.1
  # https://pub.dev/packages/drift_flutter
  drift_flutter: ^0.2.6
  # https://pub.dev/packages/fullscreen_window
  fullscreen_window: ^1.1.0
  # https://pub.dev/packages/animated_reorderable_list/
  animated_reorderable_list: ^1.3.0
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.5
  # https://pub.dev/packages/path/
  path: ^1.9.1
  # https://pub.dev/packages/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.7.0
  # https://pub.dev/packages/flutter_gen
  flutter_gen: ^5.11.0
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.2.1
  # https://pub.dev/packages/visibility_detector
  visibility_detector: ^0.4.0+2
    # https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: ^19.4.2
  # https://pub.dev/packages/logging
  logging: ^1.3.0
  # https://pub.dev/packages/firebase_core
  firebase_core: ^4.1.0
  # https://pub.dev/packages/firebase_messaging
  firebase_messaging: ^16.0.1  
  # https://pub.dev/packages/device_info_plus
  device_info_plus: ^12.1.0
  # https://pub.dev/packages/google_maps_flutter
  google_maps_flutter: ^2.13.1
  # https://pub.dev/packages/geolocator
  geolocator: ^14.0.2
  # https://pub.dev/packages/geocoding
  geocoding: ^4.0.0
  # https://pub.dev/packages/permission_handler
  permission_handler: ^12.0.1

dependency_overrides:
  analyzer: 8.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: '10.0.5' # for Dart 3.3 use ^9.0.0
  # https://pub.dev/packages/build_runner
  build_runner: ^2.7.1
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.11.1
  # https://pub.dev/packages/freezed
  freezed: ^3.2.3
  # https://pub.dev/packages/riverpod_generator
  riverpod_generator: ^3.0.0
  # https://pub.dev/packages/envied_generator
  envied_generator: ^1.2.1
  # https://pub.dev/packages/drift_dev
  drift_dev: ^2.28.2
  # https://pub.dev/packages/flutter_gen_runner
  flutter_gen_runner: ^5.11.0
  

flutter:
  uses-material-design: true

